language: python
python:
- '2.7'
- '3.3'
- '3.4'
install: pip install -r requirements.txt
script: coverage run manage.py test --settings=sample_project.settings.test
env:
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXX TWILIO_AUTH_TOKEN=YYYYYYYYYYYYYYYYYY
